name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Single .env file creation with all needed variables
      - name: Create environment file
        run: |
          cat << EOF > .env
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
          NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/
          NODE_ENV=test
          EOF

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Build Next.js app
        run: npm run build

      - name: Run Playwright tests
        run: |
          echo "Debug: Checking environment setup"
          if [ -f ".env" ]; then
            echo "✓ .env file exists"
            echo "✓ Checking Clerk key presence (not showing value):"
            if grep -q "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" .env; then
              echo "✓ NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is set"
            fi
          else
            echo "✗ .env file missing"
          fi
          npm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30