name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    env:
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_Y2xlcmsuY29t"
    CLERK_SECRET_KEY: "sk_test_Y2xlcmsuY29t"
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: "/"
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: "/"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test directory
        run: mkdir -p __tests__

      - name: Create sample test
        run: |
          echo "describe('Sample Test', () => { it('should pass', () => { expect(true).toBe(true); }); });" > __tests__/sample.test.ts

      - name: Run tests
        run: npm test

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build

      - name: Run Playwright tests
        run: npm run test:e2e
